### ISSUE TITLE
change locations page

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#136] opened 2024-04-18 13:57 UTC
no need for districts to be shown, but rather the exact location of the grocery shop

**Comment by kisram** [comment] 2024-04-22 08:16
They will fill out the lat and long columns in the Documents table in Baserow. There seems to have been a misunderstanding about what the markers on the Locations map represent

**Comment by kisram** [comment] 2024-04-24 08:41
also instead of the different colours for location types, there should be two colours for the two centuries, e.g. red for the 19th century, blue for 18th century. We should put the centuries on layers that you can select (either 18th, 19th or both)

**Comment by kisram** [comment] 2024-07-31 08:34
We finally have some documents with lat and long data, so it's time to start working on the new locations page

**Comment by kisram** [comment] 2024-08-05 13:05
I have been thinking about it and since they would like a map that represents the locations of Documents/ Grocers, but don't want the Districts etc to be represented on the map, I feel like we should just keep the Locations table as it is, remove the map and instead add a map to the Documents page.

**Comment by kisram** [comment] 2024-08-22 13:17
Trying to think of a solution for overlapping markers, at least two of the documents (Document 39 and 44) have the exact same coordinates

**Comment by kisram** [comment] 2024-08-23 09:34
Spiderfy works, just need to modify the default behaviour where the markers are only spiderfied if they are clicked. 
+ solve some weird behaviour that filtering creates
![image](https://github.com/user-attachments/assets/76e223b3-2dc9-4351-97c1-b872d71baf3a)
![image](https://github.com/user-attachments/assets/bc8af1c3-ff11-4504-97ca-b8cc722448bb)

**Comment by kisram** [comment] 2024-08-23 10:20
Solved the weird behaviour, but spiderfying by default is proving to be difficult. I tried simulating a click, but it doesn't work because clicking on another marker will unspiderfy the previously spiderfied markers. Maybe a mixed-colour marker is the way to go after all...

**Comment by kisram** [comment] 2024-08-23 12:45
I confirmed that for now there are only those 2 markers overlapping, so only those are clicked. I will be closing this issue and adding a new issue for overlapping markers. I think for now it's okay if we keep an eye on it and figure out a better solution if we get more Documents with the same coordinates.

**Closed** 2024-08-23 12:47 UTC
